const editor = document.getElementById("editor");
const charCount = document.getElementById("charCount");
const submitButton = document.getElementById("submitButton");

function updateCharCount() {
  const remaining = 1000 - editor.value.length;
  charCount.textContent = `Characters remaining: ${remaining}`;
}

function autoResize() {
  this.style.height = "auto";
  this.style.height = this.scrollHeight + "px";
}

editor.addEventListener("input", () => {
  updateCharCount();
  autoResize.call(editor);
});

// Prevent right-click and copy/paste
document.addEventListener("contextmenu", (e) => e.preventDefault());
document.addEventListener("keydown", (e) => {
  if ((e.ctrlKey || e.metaKey) && (e.key === "c" || e.key === "v")) {
    e.preventDefault();
  }
});

// Add this function at the top of your file
function generateUID() {
  return Date.now().toString(36) + Math.random().toString(36).substr(2);
}

// Add this line right after your existing const declarations
const uidInput = document.getElementById("uid");

// Set the UID when the page loads
uidInput.value = generateUID();

submitButton.addEventListener("click", () => {
  const text = editor.value.trim();
  if (text.length === 0) {
    alert("Text editor is empty!");
    return;
  }

  const doc = new jspdf.jsPDF();

  // Add "Save from really?" text at the top in purple
  doc.setTextColor(128, 0, 128); // Purple color
  doc.text("Generated by human", 15, 15);

  // Reset text color to black for the main content
  doc.setTextColor(0, 0, 0);
  const splitText = doc.splitTextToSize(text, 180);
  doc.text(splitText, 15, 25);

  // Add UID at the bottom of the page
  doc.setFontSize(8);
  doc.text(`UID: ${uidInput.value}`, 15, doc.internal.pageSize.height - 10);

  doc.save("wrote_by_human.pdf");
});
